[tool.poetry]
name = "poetry-app"
version = "0.1.0"
description = ""
authors = ["Eadweard <aurora.coder.zqf@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11.2"
flask = "^3.0.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
